apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
  namespace: default
type: Opaque
data:
  password: c3VwZXJzZWNyZXQ=
---
apiVersion: v1
kind: Secret
metadata:
  name: tls-cert
  namespace: default
type: kubernetes.io/tls
data:
  tls.crt: ZmFrZWNlcnQ=
  tls.key: ZmFrZWtleQ==
---
apiVersion: v1
kind: Secret
metadata:
  name: registry-credentials
  namespace: default
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: e30=
---
apiVersion: v1
kind: Secret
metadata:
  name: sa-token
  namespace: default
type: kubernetes.io/service-account-token
data:
  token: ZmFrZXRva2Vu
